### ISSUE TITLE
How to build the solution with VS2019?

### ISSUE THREAD

**Issue by ZedZipDev** [SQL-MisterMagoo/BlazorBinding#10]
I have tried to build the solution in VS2019 but it fails.
How to fix and build it?

There are errors:

> >obj\Debug\netstandard2.0\RazorDeclaration\App.razor.g.cs(64,91,64,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Shared\NavMenu.razor.g.cs(64,91,64,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\CascadeCallback.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\CascadeCallback.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(70,38,70,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(70,38,70,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Shared\MainLayout.razor.g.cs(64,91,64,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(75,91,75,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleBinding.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleBinding.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\CascadeCallback.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleBinding.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\DialogDemo.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\DialogDemo.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\DialogDemo.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\AutoComplete\AutoComplete.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\TheProblemWithClicks.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\TheProblemWithClicks.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleBindingCallback.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleBindingCallback.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Readme.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Readme.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleCascade.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleCascade.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\TheProblemWithClicks.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleBindingCallback.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Readme.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBinding.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBinding.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingCallback.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingCallback.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Suggestion.razor.g.cs(75,38,75,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Suggestion.razor.g.cs(75,38,75,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBinding.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingCallback.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\_Imports.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\_Imports.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\SimpleCascade.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingClassCallbackRefresh.razor.g.cs(70,38,70,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingClassCallbackRefresh.razor.g.cs(70,38,70,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingCallbackRefresh.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingCallbackRefresh.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\Suggestion.razor.g.cs(80,91,80,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingCallbackRefresh.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ValueBindingClassCallbackRefresh.razor.g.cs(75,91,75,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\CheckBox.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\CheckBox2.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\CheckBox3.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\CheckBox4.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\CheckBox6.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ViewModelBinding.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ViewModelBinding.razor.g.cs(65,38,65,53): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Pages\ViewModelBinding.razor.g.cs(70,91,70,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\MMDialog.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\CheckBox5.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\DocumentationSupport\Card.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\ListView.razor.g.cs(68,91,68,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>obj\Debug\netstandard2.0\RazorDeclaration\Components\DocumentationSupport\DisplayCode.razor.g.cs(73,91,73,108): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)
1>Done building project "BlazorBinding.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by SQL-MisterMagoo** [comment]
What does `dotnet --version` report when run from the solution folder?

**Comment by ZedZipDev** [comment]
3.1.100

**Comment by ZedZipDev** [comment]
By the way VS shows 
Microsoft.AspNetCore.Components.RenderTreeBuilder exists
but not 
'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering'

**Comment by SQL-MisterMagoo** [comment]
Sorry I was thinking of a different project - this one needs to be updated - give me 1/2 hour

**Comment by ZedZipDev** [comment]
Ok, np, and Happy New Year! :)
